/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ImagePath;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * TvListResultObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-03T23:12:37.025-03:00[America/Sao_Paulo]")
public class TvListResultObject {
  @SerializedName("poster_path")
  private ImagePath posterPath = null;

  @SerializedName("popularity")
  private BigDecimal popularity = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("backdrop_path")
  private ImagePath backdropPath = null;

  @SerializedName("vote_average")
  private BigDecimal voteAverage = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("first_air_date")
  private String firstAirDate = null;

  @SerializedName("origin_country")
  private List<String> originCountry = null;

  @SerializedName("genre_ids")
  private List<Integer> genreIds = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("original_name")
  private String originalName = null;

  public TvListResultObject posterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @Schema(description = "")
  public ImagePath getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
  }

  public TvListResultObject popularity(BigDecimal popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @Schema(description = "")
  public BigDecimal getPopularity() {
    return popularity;
  }

  public void setPopularity(BigDecimal popularity) {
    this.popularity = popularity;
  }

  public TvListResultObject id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TvListResultObject backdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
    return this;
  }

   /**
   * Get backdropPath
   * @return backdropPath
  **/
  @Schema(description = "")
  public ImagePath getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
  }

  public TvListResultObject voteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
    return this;
  }

   /**
   * Get voteAverage
   * @return voteAverage
  **/
  @Schema(description = "")
  public BigDecimal getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
  }

  public TvListResultObject overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @Schema(description = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public TvListResultObject firstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
    return this;
  }

   /**
   * Get firstAirDate
   * @return firstAirDate
  **/
  @Schema(description = "")
  public String getFirstAirDate() {
    return firstAirDate;
  }

  public void setFirstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
  }

  public TvListResultObject originCountry(List<String> originCountry) {
    this.originCountry = originCountry;
    return this;
  }

  public TvListResultObject addOriginCountryItem(String originCountryItem) {
    if (this.originCountry == null) {
      this.originCountry = new ArrayList<String>();
    }
    this.originCountry.add(originCountryItem);
    return this;
  }

   /**
   * Get originCountry
   * @return originCountry
  **/
  @Schema(description = "")
  public List<String> getOriginCountry() {
    return originCountry;
  }

  public void setOriginCountry(List<String> originCountry) {
    this.originCountry = originCountry;
  }

  public TvListResultObject genreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
    return this;
  }

  public TvListResultObject addGenreIdsItem(Integer genreIdsItem) {
    if (this.genreIds == null) {
      this.genreIds = new ArrayList<Integer>();
    }
    this.genreIds.add(genreIdsItem);
    return this;
  }

   /**
   * Get genreIds
   * @return genreIds
  **/
  @Schema(description = "")
  public List<Integer> getGenreIds() {
    return genreIds;
  }

  public void setGenreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
  }

  public TvListResultObject originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @Schema(description = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public TvListResultObject voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @Schema(description = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }

  public TvListResultObject name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TvListResultObject originalName(String originalName) {
    this.originalName = originalName;
    return this;
  }

   /**
   * Get originalName
   * @return originalName
  **/
  @Schema(description = "")
  public String getOriginalName() {
    return originalName;
  }

  public void setOriginalName(String originalName) {
    this.originalName = originalName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TvListResultObject tvListResultObject = (TvListResultObject) o;
    return Objects.equals(this.posterPath, tvListResultObject.posterPath) &&
        Objects.equals(this.popularity, tvListResultObject.popularity) &&
        Objects.equals(this.id, tvListResultObject.id) &&
        Objects.equals(this.backdropPath, tvListResultObject.backdropPath) &&
        Objects.equals(this.voteAverage, tvListResultObject.voteAverage) &&
        Objects.equals(this.overview, tvListResultObject.overview) &&
        Objects.equals(this.firstAirDate, tvListResultObject.firstAirDate) &&
        Objects.equals(this.originCountry, tvListResultObject.originCountry) &&
        Objects.equals(this.genreIds, tvListResultObject.genreIds) &&
        Objects.equals(this.originalLanguage, tvListResultObject.originalLanguage) &&
        Objects.equals(this.voteCount, tvListResultObject.voteCount) &&
        Objects.equals(this.name, tvListResultObject.name) &&
        Objects.equals(this.originalName, tvListResultObject.originalName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posterPath, popularity, id, backdropPath, voteAverage, overview, firstAirDate, originCountry, genreIds, originalLanguage, voteCount, name, originalName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TvListResultObject {\n");
    
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    firstAirDate: ").append(toIndentedString(firstAirDate)).append("\n");
    sb.append("    originCountry: ").append(toIndentedString(originCountry)).append("\n");
    sb.append("    genreIds: ").append(toIndentedString(genreIds)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    originalName: ").append(toIndentedString(originalName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
